//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop_Lebedeva.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDEmploee { get; set; }
        public int IDService { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime TheEnd { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Emploee Emploee { get; set; }
        public virtual Service Service { get; set; }
    }
}
